
export const idBadgeInput = `name,gradYr,school,pronouns,profile
Pepito Hurler,2028,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Pepito
Gordon Harlick,2026,School of Fluid Dynamics,They/Them,https://i.pravatar.cc/150?u=Gordon
Dedra Riddett,2029,School of Advanced Mathematics,prefer not to say,https://i.pravatar.cc/150?u=Dedra
Ursala Bywater,2027,School of Hard Knocks,He/Him,https://i.pravatar.cc/150?u=Ursala
Ferdie Cunniff,2029,School of Medicine,She/Her,https://i.pravatar.cc/150?u=Ferdie
Leanor Stickel,2029,School of Words and Letters,She/Her,https://i.pravatar.cc/150?u=Leanor
Wendell Isaacs,2029,School of Advanced Mathematics,He/Him,https://i.pravatar.cc/150?u=Wendell
Fair Demkowicz,2027,School of Fluid Dynamics,prefer not to say,https://i.pravatar.cc/150?u=Fair
Daisey Munnis,2026,School of Words and Letters,prefer not to say,https://i.pravatar.cc/150?u=Daisey
Karena Conelly,2027,School of Hard Knocks,She/Her,https://i.pravatar.cc/150?u=Karena
Cleavland Chillingsworth,2026,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Cleavland
Ettore Buey,2026,School of Data Science,They/Them,https://i.pravatar.cc/150?u=Ettore
Tracie Briamo,2029,School of Hard Knocks,She/Her,https://i.pravatar.cc/150?u=Tracie
Aprilette Mundwell,2026,School of Data Science,He/Him,https://i.pravatar.cc/150?u=Aprilette
Dukey Cerro,2027,School of Words and Letters,They/Them,https://i.pravatar.cc/150?u=Dukey
Corey Carlozzi,2026,School of Medicine,She/Her,https://i.pravatar.cc/150?u=Corey
Mariejeanne Corran,2028,School of Data Science,They/Them,https://i.pravatar.cc/150?u=Mariejeanne
Denice Vasiljevic,2029,School of Fluid Dynamics,She/Her,https://i.pravatar.cc/150?u=Denice
Suzann Brocket,2029,School of Fluid Dynamics,She/Her,https://i.pravatar.cc/150?u=Suzann
Lowrance Morrow,2028,School of Words and Letters,He/Him,https://i.pravatar.cc/150?u=Lowrance
Anson Culkin,2029,School of Fluid Dynamics,They/Them,https://i.pravatar.cc/150?u=Anson
Townie Cremin,2027,School of Hard Knocks,prefer not to say,https://i.pravatar.cc/150?u=Townie
Lila Hamm,2027,School of Words and Letters,They/Them,https://i.pravatar.cc/150?u=Lila
Effie Hammersley,2027,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Effie
Lauraine Kubica,2027,School of Hard Knocks,He/Him,https://i.pravatar.cc/150?u=Lauraine
Dion Alu,2029,School of Words and Letters,They/Them,https://i.pravatar.cc/150?u=Dion
Edith Whitloe,2029,School of Medicine,They/Them,https://i.pravatar.cc/150?u=Edith
Adoree McRamsey,2026,School of Data Science,prefer not to say,https://i.pravatar.cc/150?u=Adoree
Nikita Pochin,2026,School of Advanced Mathematics,She/Her,https://i.pravatar.cc/150?u=Nikita
Denis Dunkerley,2026,School of Fluid Dynamics,She/Her,https://i.pravatar.cc/150?u=Denis
Karlee Hyde,2027,School of Fluid Dynamics,She/Her,https://i.pravatar.cc/150?u=Karlee
Worden Scini,2027,School of Medicine,They/Them,https://i.pravatar.cc/150?u=Worden
Mirabella Scown,2027,School of Data Science,They/Them,https://i.pravatar.cc/150?u=Mirabella
Charmion Izhaky,2028,School of Medicine,He/Him,https://i.pravatar.cc/150?u=Charmion
Hervey Devanny,2027,School of Fluid Dynamics,He/Him,https://i.pravatar.cc/150?u=Hervey
Bobinette Soigoux,2029,School of Words and Letters,He/Him,https://i.pravatar.cc/150?u=Bobinette
Othelia Jemmison,2028,School of Hard Knocks,He/Him,https://i.pravatar.cc/150?u=Othelia
Inger Symondson,2029,School of Data Science,prefer not to say,https://i.pravatar.cc/150?u=Inger
Georges Domeny,2028,School of Fluid Dynamics,He/Him,https://i.pravatar.cc/150?u=Georges
Wenonah Pretti,2028,School of Data Science,prefer not to say,https://i.pravatar.cc/150?u=Wenonah
Dov Kunrad,2026,School of Hard Knocks,She/Her,https://i.pravatar.cc/150?u=Dov
Jessie Growcock,2029,School of Data Science,They/Them,https://i.pravatar.cc/150?u=Jessie
Dorry Necolds,2028,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Dorry
Shauna Sextone,2027,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Shauna
Manda Christescu,2028,School of Advanced Mathematics,prefer not to say,https://i.pravatar.cc/150?u=Manda
Chane Malenfant,2028,School of Fluid Dynamics,prefer not to say,https://i.pravatar.cc/150?u=Chane
Carlo Lulham,2029,School of Medicine,She/Her,https://i.pravatar.cc/150?u=Carlo
Fredric Worland,2029,School of Advanced Mathematics,He/Him,https://i.pravatar.cc/150?u=Fredric
Renard Niece,2026,School of Hard Knocks,She/Her,https://i.pravatar.cc/150?u=Renard
Georas Urvoy,2029,School of Medicine,They/Them,https://i.pravatar.cc/150?u=Georas
Sisely Longthorne,2027,School of Hard Knocks,They/Them,https://i.pravatar.cc/150?u=Sisely
Adeline Goretti,2026,School of Fluid Dynamics,They/Them,https://i.pravatar.cc/150?u=Adeline
Ezechiel Popov,2028,School of Medicine,He/Him,https://i.pravatar.cc/150?u=Ezechiel
Benedict Roddick,2026,School of Advanced Mathematics,They/Them,https://i.pravatar.cc/150?u=Benedict
Jilleen Stuttard,2029,School of Medicine,They/Them,https://i.pravatar.cc/150?u=Jilleen
Gaile Anthon,2028,School of Hard Knocks,He/Him,https://i.pravatar.cc/150?u=Gaile
Ado Boxhill,2026,School of Fluid Dynamics,She/Her,https://i.pravatar.cc/150?u=Ado
Eldredge Bollis,2027,School of Data Science,He/Him,https://i.pravatar.cc/150?u=Eldredge
Huntley Langeren,2026,School of Words and Letters,He/Him,https://i.pravatar.cc/150?u=Huntley
Klarika Peizer,2026,School of Medicine,They/Them,https://i.pravatar.cc/150?u=Klarika
Jarad Asplin,2028,School of Data Science,He/Him,https://i.pravatar.cc/150?u=Jarad
Beale Rickford,2026,School of Words and Letters,He/Him,https://i.pravatar.cc/150?u=Beale
Taite Pickford,2026,School of Fluid Dynamics,She/Her,https://i.pravatar.cc/150?u=Taite
Duane Halms,2029,School of Medicine,He/Him,https://i.pravatar.cc/150?u=Duane
Harmonie Ricart,2028,School of Hard Knocks,They/Them,https://i.pravatar.cc/150?u=Harmonie
Thedric Highman,2029,School of Advanced Mathematics,They/Them,https://i.pravatar.cc/150?u=Thedric
Cathrin Showers,2026,School of Advanced Mathematics,She/Her,https://i.pravatar.cc/150?u=Cathrin
Dorian Indge,2028,School of Hard Knocks,They/Them,https://i.pravatar.cc/150?u=Dorian
Maddalena Lansdale,2027,School of Data Science,prefer not to say,https://i.pravatar.cc/150?u=Maddalena
Sybila Belvin,2029,School of Advanced Mathematics,She/Her,https://i.pravatar.cc/150?u=Sybila
Etan Atwel,2029,School of Advanced Mathematics,She/Her,https://i.pravatar.cc/150?u=Etan
Ardra Creeber,2029,School of Medicine,prefer not to say,https://i.pravatar.cc/150?u=Ardra
Tessa Claybourn,2027,School of Medicine,He/Him,https://i.pravatar.cc/150?u=Tessa
Derrick Revel,2026,School of Fluid Dynamics,prefer not to say,https://i.pravatar.cc/150?u=Derrick
Tatiania Goulding,2028,School of Medicine,He/Him,https://i.pravatar.cc/150?u=Tatiania
Maggee Audus,2028,School of Advanced Mathematics,They/Them,https://i.pravatar.cc/150?u=Maggee
Florenza Vedikhov,2026,School of Fluid Dynamics,He/Him,https://i.pravatar.cc/150?u=Florenza
Otes Conerding,2026,School of Hard Knocks,He/Him,https://i.pravatar.cc/150?u=Otes
Bendick Millard,2026,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Bendick
Paulo Smiths,2029,School of Hard Knocks,He/Him,https://i.pravatar.cc/150?u=Paulo
Tiphanie Stonall,2029,School of Hard Knocks,She/Her,https://i.pravatar.cc/150?u=Tiphanie
Regina Darkins,2026,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Regina
Karim Hurst,2026,School of Hard Knocks,She/Her,https://i.pravatar.cc/150?u=Karim
Dorette Cicchitello,2028,School of Advanced Mathematics,She/Her,https://i.pravatar.cc/150?u=Dorette
Shani Sidebotham,2027,School of Medicine,He/Him,https://i.pravatar.cc/150?u=Shani
Granger Scholling,2028,School of Hard Knocks,They/Them,https://i.pravatar.cc/150?u=Granger
Rita Playden,2026,School of Medicine,She/Her,https://i.pravatar.cc/150?u=Rita
Marshall Fleetwood,2027,School of Words and Letters,prefer not to say,https://i.pravatar.cc/150?u=Marshall
Liesa Kobierzycki,2026,School of Words and Letters,They/Them,https://i.pravatar.cc/150?u=Liesa
Chanda Baroch,2026,School of Medicine,She/Her,https://i.pravatar.cc/150?u=Chanda
Peggy Sarvar,2029,School of Hard Knocks,They/Them,https://i.pravatar.cc/150?u=Peggy
Debbie Fleet,2029,School of Advanced Mathematics,He/Him,https://i.pravatar.cc/150?u=Debbie
Lorelle Hubery,2028,School of Data Science,They/Them,https://i.pravatar.cc/150?u=Lorelle
Lois Flori,2027,School of Fluid Dynamics,prefer not to say,https://i.pravatar.cc/150?u=Lois
Heall Stokey,2028,School of Medicine,She/Her,https://i.pravatar.cc/150?u=Heall
Chantal Tyrwhitt,2027,School of Data Science,They/Them,https://i.pravatar.cc/150?u=Chantal
Luz Micco,2028,School of Data Science,She/Her,https://i.pravatar.cc/150?u=Luz
Muriel Craddy,2027,School of Advanced Mathematics,He/Him,https://i.pravatar.cc/150?u=Muriel
Brandais Haton,2029,School of Fluid Dynamics,He/Him,https://i.pravatar.cc/150?u=Brandais
Gilbertine Breadon,2028,School of Words and Letters,prefer not to say,https://i.pravatar.cc/150?u=Gilbertine
`.split(/\r?\n/)  //handle Windows \r\n line endings
.filter(Boolean); //remove any blanks


export const idBadgeInputExampleString = `[
${idBadgeInput.slice(0, 10).map(line => `"${line}",`).join('\n')}
]`;